@startuml Ficha

hide empty description

[*] --> FichaGenerada
FichaGenerada --> FichaImpresa
FichaImpresa --> FichaRegistrada
FichaRegistrada --> [*]

FichaGenerada : Se genera la ficha al confirmar el turno
FichaImpresa : Una vez generada, la ficha se imprime para su uso
FichaRegistrada : El encargado de taller completa los datos completos de la ficha

@enduml