@startuml Turno
 
[*] --> CreadoVacío : new()
state existeCliente <<choice>>
state clienteAsiste <<choice>>
state nuevoCliente {
   [*] --> ClienteCargado : new()
   ClienteCargado --> [*]
}
 
CreadoVacío --> existeCliente : asignarTurno()
existeCliente -left-> DatosCompletos : [existeCliente == true]
existeCliente --> nuevoCliente : [existeCliente == false]
nuevoCliente --> DatosCompletos : selectNewCliente()
DatosCompletos -left-> TurnoConfirmado : confirmarTurno()
TurnoConfirmado --> clienteAsiste : confirmarAsistencia()
clienteAsiste -left-> AsistenciaConfirmada : [clienteAsiste == true]
clienteAsiste -right-> TurnoCancelado : [clienteAsiste == false]
AsistenciaConfirmada --> [*]
TurnoCancelado -->[*]
@enduml