@startuml Diagrama Colaboracion Consultar Mecanico

allow_mixing
control "Sistema" as sist
control "ControladorMecanico" as ctrl
collections ":Mecanico" as col

sist -right-> ctrl : 1.getMecanicos(string especialización)
ctrl --> ctrl : 2.getMecanicos(string especialización)
ctrl -up-> col : 3.getMecanicos(string especialización)
ctrl -left-> sist : 4. listarMecanicos()

@enduml
